---
- name: add nginx repo from PPA
  apt_repository:
    repo: ppa:nginx/stable

- name: add docker repo GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present 

- name: add golang repo
  apt_repository:
    repo: ppa:longsleep/golang-backports

- name: add hashicorp repo GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: add hashicorp repo
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: install devserver system packages
  apt:
    name:
    - ansible
    - containerd.io
    - docker-ce
    - docker-ce-cli
    - g++
    - gdb
    - git
    - golang-go
    - make
    - nginx
    - packer
    - python3
    - sudo
    - terraform
    - zsh
    state: present
    update_cache: true

- name: download docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0775
    owner: root
    group: root

- name: download zprezto
  git:
    recursive: true
    accept_hostkey: true
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: /etc/zprezto

- name: copy zprezto repo
  copy:
    src: /etc/zprezto/
    dest: /etc/skel/.zprezto
    remote_src: true
    mode: 0775

- name: copy zprezto rc files
  copy:
    src: "/etc/zprezto/runcoms/{{ item }}"
    dest: "/etc/skel/.{{ item }}"
    remote_src: true
    mode: 0664
  loop:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc
